import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Header />

        <div className="container">{children}</div>
      </body>
    </html>
  );
}
