name: tickets-tests

on:
  pull_request:
    paths:
      - "tikcets/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
